# Generated by Django 4.2.5 on 2024-01-21 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
