# Generated by Django 4.2.5 on 2024-01-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_exercises', '0003_rename_name_exercise_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(default='Exercise', max_length=100),
        ),
    ]
