# Generated by Django 4.2.5 on 2024-01-30 16:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_exercises", "0004_exercise_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["id"]},
        ),
    ]
