# Generated by Django 4.2.5 on 2024-01-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_accounts", "0003_alter_customuser_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(blank=True),
        ),
    ]
