# Generated by Django 4.2.5 on 2024-01-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_accounts", "0004_customuser_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
