# Generated by Django 4.2.5 on 2024-01-30 16:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("app_accounts", "0005_alter_customuser_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userexerciseconversation",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="userexerciseconversation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="userexerciseconversation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
