# Generated by Django 4.2.5 on 2024-01-31 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_accounts", "0007_alter_userexerciseconversation_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userexerciseconversation",
            old_name="message",
            new_name="body",
        ),
        migrations.RemoveField(
            model_name="userexerciseconversation",
            name="is_human",
        ),
        migrations.RemoveField(
            model_name="userexerciseconversation",
            name="user",
        ),
        migrations.AddField(
            model_name="userexerciseconversation",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userexerciseconversation",
            name="sent_by",
            field=models.CharField(default="client", max_length=255),
        ),
    ]
